eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10089/eureka/
server:
  port: 11019
spring:
  zipkin:
      base-url: http://localhost:9411
  sleuth:
      sampler:
          percentage: 1.0
  application:
    name: eurekaclient
  

    
